### ISSUE TITLE
Decompressing with pigz is not parallel

### ISSUE THREAD

**Issue by scottchiefbaker** [madler/pigz#36]
If I decompress a file with `pigz -d foo.gz` it only uses one core, on my multicore system. Compressing uses **all** my cores, but decompressing does not. Is this by design? I'm trying to compare decompression speeds or `pigz` vs vs `pbzip2` vs `lz4`.

`pbzip2` does mutli-threaded decompression so I assumed pigz would too.

    :cat /tmp/d8.qcow.lz4 | pv | lz4 -d > /dev/null
    936MiB 0:00:06 [ 152MiB/s]

    :cat /tmp/d8.qcow.gz | pv | pigz -d > /dev/null
    705MiB 0:00:12 [  56MiB/s]

    :cat /tmp/d8.qcow.bz2 | pv | pbzip2 -d > /dev/null
    637MiB 0:00:04 [ 129MiB/s]

**Comment by madler** [comment]
From the documentation:

Decompression can’t be parallelized, at least not without specially prepared deflate streams for that purpose. As a result, pigz uses a single thread (the main thread) for decompression, but will create three other threads for reading, writing, and check calculation, which can speed up decom- pression under some circumstances.

**Comment by scottchiefbaker** [comment]
That's about what I figured. Do you know how `pbzip2` handles multi-threaded decompression? Is there something inherent in the `bzip2` algorithm that makes it possible?

**Comment by madler** [comment]
It is something inherent in the bzip2 _format_. Each of the bzip2 blocks can be decompressed independently, and most importantly there is a 48-bit constant (the first 12 digits of pi in BCD) before every block. That facilitates a parallel decompressor quickly finding where it can break up a bzip2 file into pieces.

**Comment by bjmgeek** [comment]
What about the case where I would like to decompress a lot of .gz files?  That should be multithreadable...

**Comment by chrchang** [comment]
@Code7R : something similar to the approach you describe has been widely used in bioinformatics for close to a decade: see the BGZF format (section 4.1 of https://samtools.github.io/hts-specs/SAMv1.pdf ).  I've written code which detects BGZF and opportunistically launches multiple decompressor threads.

The drawback, at least with BGZF, is inferior compression due to the low block size limit (64K).  ~15-20% file bloat is not uncommon (see https://blastedbio.blogspot.com/2011/11/bgzf-blocked-bigger-better-gzip.html ).  If that's too much, but you really need both gzip compatibility and high-speed decompression, you could design a BGZF-like format with a block size in the 1-16 MB range.

**Comment by gwfrere** [comment]
> Yes, I suppose I could implement that. However that is already possible simply with multiple instances of pigz, or gzip for that matter. xargs or [GNU parallel](https://www.gnu.org/software/parallel/) would help facilitate that.

Hi Mark. I use GNU parallel and pgiz. I want to make sure this is still your recommended method for decompression of many gz files?

**Comment by neurolabusc** [comment]
@gwfrere pigz is not particularly faster than gzip for decompressing files, as each file is decompressed in serial. If you are decompressing multiple files simultaneously, any method for asynchronously calling these tools (including GNU parallel) will work.

1. If you are compressing the files you will decompress, and are using Python, you might want to take a look at [mgzip](https://pypi.org/project/mgzip/). It uses gzip-compatible concatenated gz files (a similar strategy to BGZF), so that gzip will compress files in parallel and can also decompress files it creates in parallel. Gzip files created by other tools are decompressed in serial, and files created by mgzip will be decompressed in serial by other tools.

By the way, if you compile pigz using zlib-ng rather than zlib, [decompression](https://github.com/neurolabusc/pigz-bench-python) will be about 10% faster. The speed benefit is pretty small, and beware that the current release of zlib-ng has issues with pigz [when dealing with level 1 compressed files](https://github.com/zlib-ng/zlib-ng/issues/536).

**Comment by mxmlnkn** [comment]
> It is something inherent in the bzip2 _format_. Each of the bzip2 blocks can be decompressed independently, and most importantly there is a 48-bit constant (the first 12 digits of pi in BCD) before every block. That facilitates a parallel decompressor quickly finding where it can break up a bzip2 file into pieces.

Actually, thanks to pigz using `Z_SYNC_FLUSH`, there is a 35-bit-string, which is even known to be byte-aligned after the first three bits!

>   If the parameter flush is set to Z_SYNC_FLUSH, all pending output is
  flushed to the output buffer and the output is aligned on a byte boundary, so
  that the decompressor can get all input data available so far.  (In
  particular avail_in is zero after the call if enough output space has been
  provided before the call.) Flushing may degrade compression for some
  compression algorithms and so it should be used only when necessary.  This
  completes the current deflate block and follows it with an empty stored block
  that is three bits plus filler bits to the next byte, followed by four bytes
  (00 00 ff ff).

These flush markers can be searched quite reliably in my current prototype. My hope is that I can then begin decoding from there. I'm hoping to hack something together soon to improve performance for [ratarmount](https://github.com/mxmlnkn/ratarmount), probably something based on my parallelized bzip2 decoder [indexed_bzip2](https://github.com/mxmlnkn/indexed_bzip2) written in C++. But, I think, it would be nice to see this implemented in pigz itself (if I'm not completely wrong with this)!

As for the probability of false positives. We basically have a 2^32 number byte-aligned number `00 00 FF FF`, which comes out to one match every 4GiB of random data. Furthermore, because of the preceding block header, we can check that the three bits preceding are all zero, which adds another probability of 1/8, so now we would have one false positive every 32GiB. But furthermore, this magic bit string has quite low entropy and therefore is "unlikely" to appear in valid gzip compressed data. So the probability for false positives might be even less or even impossible? I don't know but the false positive rate definitely seems good enough to yield very nice speedups when correctly error checking and ignoring the rare false positive.

**Comment by mxmlnkn** [comment]
I finally have a prototype ([rapidgzip](https://github.com/mxmlnkn/rapidgzip)) that can parallelize the decoding of bgzf files, pigz files, and arbitrary gzip files, for which an index created by [`indexed_gzip`](https://github.com/pauldmccarthy/indexed_gzip) may or may not exist.

Using a Ryzen 3900X, [rapidgzip](https://github.com/mxmlnkn/rapidgzip) is not only almost 10x faster than gzip decoding in these test conditions, it also offers random seeking inside the files! The latter speeds up reading via [ratarmount](https://github.com/mxmlnkn/ratarmount).

rapidgzip is a gzip decoder that was completely written from scratch using the gzip and deflate RFCs. Unfortunately, that's why the serial decoder is not very fast yet even though I already spent some time iterating over different Huffman decoder optimizations. 
However, when the back-reference window is known, as is the case when an index file exists, e.g., like in ratarmount, then decoding can be delegated to zlib resulting in another 2x speedup over my self-written decoder and resulting in competitive speeds.

You can build rapidgzip like this:

```bash
git clone https://github.com/mxmlnkn/indexed_bzip2
cd indexed_bzip2 && mkdir build && cd build && cmake .. && make rapidgzip
```

Now you can use `src/tools/rapidgzip` inside the build folder.

Here are the benchmarks I did:

```bash
sudo apt install pigz isal tabix

# Create a compressible random file
base64 /dev/urandom | head -c $(( 4 * 1024 * 1024 * 1024 )) > 4GiB-base64
fname='4GiB-base64'
pigz  -k -c "$fname" > "$fname.pigz"
bgzip    -c "$fname" > "$fname.bgz"
gzip  -k -c "$fname" > "$fname.gz"
igzip -k -c "$fname" > "$fname.igz"

printf '\n| %6s | %19s | %10s | %18s |\n' Format Decoder 'Runtime / s' 'Bandwidth / (MB/s)'
printf -- '|--------|---------------------|-------------|--------------------|\n'
for tool in cat fcat; do
    runtime=$( ( time $tool "$fname" | wc -c ) 2>&1 | sed -n -E 's|real[ \t]*0m||p' | sed 's|[ \ts]||' )
    bandwidth=$( python3 -c "print( int( round( $fileSize / 1e6 / $runtime ) ) )" )
    printf '| %6s | %19s | %11s | %18s |\n' "" "$tool" "$runtime" "$bandwidth"
done

fname='4GiB-base64'
fileSize=$( stat -L --format=%s "$fname" )
for format in gz bgz pigz igz; do
    printf '\n| %6s | %13s | %10s | %18s |\n' Format Decoder 'Runtime / s' 'Bandwidth / (MB/s)'
    printf -- '|--------|---------------|-------------|--------------------|\n'
    crc32 "$fname.$format" &>/dev/null  # Make my QLC SSD cache the file into the SLC cache

    for tool in gzip bgzip "bgzip -@ $( nproc )" pigz igzip "igzip -T $( nproc )" "src/tools/rapidgzip -P 1" "src/tools/rapidgzip -P $( nproc )"; do
        runtime=$( ( time $tool -d -c "$fname.$format" | wc -c ) 2>&1 | sed -n -E 's|real[ \t]*0m||p' | sed 's|[ \ts]||' )
        bandwidth=$( python3 -c "print( int( round( $fileSize / 1e6 / $runtime ) ) )" )
        printf '| %6s | %13s | %11s | %18s |\n' "$format" "${tool#src/tools/}" "$runtime" "$bandwidth"
    done
done
```

Results on my Ryzen 3900X (12 core / 24 virtual cores)):

| Format |       Decoder | Runtime / s | Bandwidth / (MB/s) |
|--------|---------------|-------------|--------------------|
|        |           cat |       1.273 |               3374 |
|        |          fcat |       0.503 |               8539 |


| Format |       Decoder | Runtime / s | Bandwidth / (MB/s) |
|--------|---------------|-------------|--------------------|
|     gz |          gzip |      22.218 |                193 |
|     gz |         bgzip |      16.202 |                265 |
|     gz |   bgzip -@ 24 |      15.962 |                269 |
|     gz |          pigz |      13.391 |                321 |
|     gz |         igzip |       9.225 |                466 |
|     gz |   igzip -T 24 |       9.295 |                462 |
|     gz | rapidgzip -P 1 |       8.811 |                487 |
|     gz | rapidgzip -P 24 |       1.320 |               **3254** |

| Format |       Decoder | Runtime / s | Bandwidth / (MB/s) |
|--------|---------------|-------------|--------------------|
|    bgz |          gzip |      21.346 |                201 |
|    bgz |         bgzip |      10.621 |                404 |
|    bgz |   bgzip -@ 24 |       1.949 |               2204 |
|    bgz |          pigz |      18.466 |                233 |
|    bgz |         igzip |       7.321 |                587 |
|    bgz |   igzip -T 24 |       7.377 |                582 |
|    bgz | rapidgzip -P 1 |       7.520 |                571 |
|    bgz | rapidgzip -P 24 |       1.125 |               **3818** |

| Format |       Decoder | Runtime / s | Bandwidth / (MB/s) |
|--------|---------------|-------------|--------------------|
|   pigz |          gzip |      24.320 |                177 |
|   pigz |         bgzip |      16.358 |                263 |
|   pigz |   bgzip -@ 24 |      15.868 |                271 |
|   pigz |          pigz |      13.404 |                320 |
|   pigz |         igzip |       9.709 |                442 |
|   pigz |   igzip -T 24 |       9.491 |                453 |
|   pigz | rapidgzip -P 1 |       8.867 |                484 |
|   pigz | rapidgzip -P 24 |       1.288 |               **3335** |

| Format |       Decoder | Runtime / s | Bandwidth / (MB/s) |
|--------|---------------|-------------|--------------------|
|    igz |          gzip |      22.809 |                188 |
|    igz |         bgzip |      15.302 |                281 |
|    igz |   bgzip -@ 24 |      15.170 |                283 |
|    igz |          pigz |      12.416 |                346 |
|    igz |         igzip |       7.836 |                548 |
|    igz |   igzip -T 24 |       7.797 |                551 |
|    igz | rapidgzip -P 1 |       7.149 |                601 |
|    igz | rapidgzip -P 24 |       1.293 |               **3322** |

The performance of igzip is pretty impressive. If I could combine that serial decoding performance with the parallel dispatching, the two-staged decoding, and the seek capability of rapidgzip, I could have something even more beautiful. 

2023-08: Right now, I have implemented ISA-L calls for many special cases, in general, as soon as no marker symbol exists anymore, i.e., if the index is imported, or for BGZF files, or for low-coherence files like the random base64. At this point the ` | wc -c` is the bottleneck for the above benchmarks even though I already use `vmsplice` to speed that up. When simply writing to `/dev/null`, it can achieve ~7.2 GB/s for 4GiB-base64.bgz and ~6.2 GB/s for 4GiB-base64.gz.

Obviously, this is a very specific kind of data. The random base64 case will lead to very few back-references, a rather small compression factor, and almost exclusively Huffman decoding being the bottleneck. The rapidgzip repository also contains benchmarks on Silesia and FASTQ files. FASTQ files are almost the worst case right now because there is no opportunity to fall back to ISA-L and because the markers require more overhead memory and work.
