### ISSUE TITLE
Is this project still actively maintained?

### ISSUE THREAD

**Issue by schuft69** [madler/pigz#48]
There are several open issues and last commit is from 2 Oct 2016.

**Comment by madler** [comment]
Update imminent.

**Comment by mschilli87** [comment]
Two years later, the same question stands (again).

Today, I hit an issue where I couldn't upgrade my system and in the end it turned out that all works fine with `gzip` but me symlinking `pigz` years ago caused the issue.
Now I'm not sure if to just work around this single case, get used to calling pigz explicitely and try gzip if it fails, or to just uninstall it.
I probably lost more time troubleshooting this than I saved by parallel (de-)compression over the last years alltogether. :disappointed: 

Coming here, I got the impression that opening an issue or attempting a PR might turn out be a waste of my time.

@madler: Please don't get this wrong. If you don't have time, fine with me. No FOSS maintainer ows me anything. But for essentials I'd rather know they work or at least somebody will try to fix them in a timely manner. :wink:

**Comment by madler** [comment]
Yes, there are many updates in the develop branch.

What is the issue?
