### ISSUE TITLE
Make -k (keep files) the default behaviour

### ISSUE THREAD

**Issue by vesnikos** [madler/pigz#61]
> I was trying to tar.gz 3 million files. 
> Midway I cancelled the operation because of reasons. 
> 300k files went awol.

Seriously though, I feel that having if a program changes the system state by default is not something that is expected by default.

**Comment by madler** [comment]
I won't be making -k the default, since that contradicts a quarter of a century of the behavior of gzip. If you like, you can make it the default for yourself by setting the GZIP or PIGZ environment variable to "-k". However it doesn't sound like using or not using the -k option on pigz has anything to do with you losing 300K files.

How exactly were you "tar.gz"ing your 3 million files? The tar command does _not_ delete the files being tarred. You have to do that yourself after the tar operation is complete, if that's what you want to do. If you were piping to pigz, then you would be piping the output as well, in which case -k would have no effect anyway. If you were tarring to a large uncompressed file and then separately applying pigz to that, then pigz -k would keep the .tar file. That again has no bearing whatsoever on the files originally tarred.

When you are using pigz to compress an individual file (not with tar), that original file is not touched until the entire compression operation is complete and the .gz file is written and closed. Only then is the original file deleted (if -k is not specified), which prevents loss of data if the operation is interrupted at any time.

Lastly, I could not parse your statement: "I feel that having if a program changes the system state by default is not something that is expected by default." Please restate it in English.

**Comment by vesnikos** [comment]
Thank you for the quick response

You are right, I was pipping the tar command to pigz, so the -k had no effect. I didn't actually lose anything. some badly written tests where failing and when I realised that I didn't pass the -k I was quick to act to put the blame elsewhere. Apologies

With my terrible written last phrase, what I meant to say was, that it feels wrong for a program to delete (by default) anything that it is given to it.  From my point of view, as a user, it certainly took me by surprise.    

I guess this sentiment, is potentially being shared by other users like myself and I guess I wanted to provide some feedback on its functionality

**Comment by madler** [comment]
gzip or pigz do not delete what is given to it by default. It _transforms_ (losslessly) what is given to it by default. You are left with the same data compressed, from which you can always reverse the process and get the original file back (in which case the compressed file is deleted).
