### ISSUE TITLE
test suite?

### ISSUE THREAD

**Issue by pieper** [madler/pigz#63]
Are there any tests that go along with pigz?

**Comment by neurolabusc** [comment]
@pieper I created a simple shell-script [benchmark](https://github.com/neurolabusc/pigz-bench) that works on Linux/MacOS. It compiles three versions of pigz (using the default zlib, zlib-ng and CloudFlare-zlib). It is really a benchmark not a test suite. You could also adapt the perl [zlib-bench](https://github.com/jsnell/zlib-bench) to test pigz. This is a bit more sophisticated as it also tests the decompression to ensure lossless conversion and measures compression ratios rather than simply timing the functions.

With regards to known issues that should be targets for thorough testing:
 -Problem with [pigz on clusters](https://github.com/madler/pigz/issues/68) that might be fixed with recent versions of glibc (since I do not have a cluster, I can not test this).

- pigz can be compiled with little modification to run on Windows. However, pigz for Windows will have issues [for non-latin characters like Описание.pdf](https://gist.github.com/przemoc/bd6c342ff7f31a0c4ec2). This can be addressed, which I will post as a new issue.

**Comment by pieper** [comment]
Thanks for digging in to this @neurolabusc 👍 

I'll wait for the answer to your [other question](https://github.com/madler/pigz/issues/62) before investing much time in pigz.

**Comment by neurolabusc** [comment]
@pieper, I think you can close this issue. I have created [Python scripts](https://github.com/neurolabusc/pigz-bench-python) that will build and test pigs using different zlib libraries. I can completely understand if you do not want to invest too much time into this, but I think this comprehensively resolves this issue.

**Comment by pieper** [comment]
Agreed - thanks for doing this 😄
