### ISSUE TITLE
Compressed file corruption when used with Intel IPP patched zlib

### ISSUE THREAD

**Issue by mike-scchen** [madler/pigz#72]
Tested on Fedora 29 and CentOS 6.
The compilers are OS-provided (8.3.1 on Fedora 29, 4.4.7 on CentOS 6).
The IPP version tested is 2019 update 4, which can be obtained from Intel freely.
The zlib I used here is 1.2.11.

Steps to reproduce the error:
1. build the patched zlib with the instructions here:
[](https://software.intel.com/en-us/articles/how-to-use-zlib-with-intel-ipp-optimization)
1. set LD_LIBRARY_PATH to make pigz (dnf install pigz) link to the patched zlib
2. ldd `which pigz` to confirm the link
3. use pigz to compress some file; no error at this stage
4. try to decompress the compressed file will give error like:
"invalid compressed data--format violated" (gzip -t), or
"corrupted -- invalid deflate data (invalid stored block lengths)" (pigz -t)
The same error happens on source-built pigz 2.4.
The zlib linking type to IPP (shared / static) did not change the behavior.

However, I've tried that said patched zlib do works with other libraries, such as HDF5.
These tools are serial, anyway; I'm not sure where the problem comes in.
Avoid using pigz with the IPP patched zlib for now.

**Comment by mgoldshteyn** [comment]
You are not the only one running into this issue. I've experienced several times as well. The problem is in some sort of synchronization bug in pigz itself. It is rare, but if you compress large enough files with enough concurrent cores, you will eventually run into it.

**Comment by neurolabusc** [comment]
@mike-scchen I can not replicate your issue. Is it possible you are using an old version of [glibc](https://github.com/madler/pigz/issues/68)? Once you have updated glibc, you can build to the selected zlib ('Intel', 'ng', 'Cloudflare', 'System'). In my experience CloudFlare outperforms the others on Intel/AMD hardware (with the exception of '-1' compression level, where Intel/ng tradeoff speed for compression ratio, so it is an apples to oranges comparison):

```
git clone https://github.com/neurolabusc/pigz.git
cd pigz
mkdir build && cd build
cmake  -DZLIB_IMPLEMENTATION=Intel ..
make
```

@mgoldshteyn is it possible that your issue is that pigs is using a [buggy version of glibc](https://github.com/madler/pigz/issues/68)? Do your issues persist if you compile pigz on a system with the latest glibc?

**Comment by madler** [comment]
I don't have access to this "patched zlib", so I cannot support it.
