### ISSUE TITLE
--force is compressing already gzipped files instead of overwriting them

### ISSUE THREAD

**Issue by jolespin** [madler/pigz#75]
This functionality didn't make sense and makes it difficult as a drop in replacement.  Could this be reprogrammed to mimic the legacy gzip? 
```

(star_env) -bash-4.1$ echo "hello" > test.txt
(star_env) -bash-4.1$ gzip -f test.txt ; ls
test.txt.gz
(star_env) -bash-4.1$ gzip -f test.txt.gz ; ls
gzip: test.txt.gz already has .gz suffix -- unchanged
test.txt.gz
(star_env) -bash-4.1$ pigz -f test.txt.gz ; ls
test.txt.gz.gz
```

**Comment by madler** [comment]
What do you mean by "instead of overwriting them"?

**Comment by jolespin** [comment]
Instead of recompressing the file it compresses the compressed file and adds an extra gzip at the end.

**Comment by madler** [comment]
I got that part. What I don't understand is that instead you are expecting the file to be overwritten?

**Comment by jolespin** [comment]
I believe the functionality of gzip -f was to overwrite the file.  Right now, the file is test.txt.gz.gz when the -f is used with pigz on test.txt.gz.  Is that the intended case to handle already gzipped files?

**Comment by madler** [comment]
gzip is in fact _not_ overwriting anything in this case. Which is why I am confused about you expecting the file to be overwritten by pigz when gzip isn't doing that.

The documentation of gzip says that `-f` will:

> Force compression or decompression even if the file has multiple links or the corresponding file already exists, or if the compressed data is read from or written to a terminal.

I could argue that gzip is not doing what the documentation says in this case, but that pigz is. pigz is forcing compression. On the other hand, I could argue that the "even if" actually was intended to mean "only if", in which case the behavior of `gzip -f` in this case is unspecified.

What is your use case that led to you considering this to be an issue?

**Comment by jolespin** [comment]
Ahh, I see what you’re saying.  It wouldn’t make sense that gzip overwrites the gzipped file because that would mean it would decompress it and then compress it again so it must just bypass this.  

What led me to this was using pigz as a drop in replacement for gzip and I realized that pigz added an extra gz to files that were already gzipped when -f was used. 

So essentially, 

gzip test.txt.gz
gzip -f test.txt.gz
pigz test.txt.gz

Are all equivalent which result in test.txt.gz while the following has unique activity:

pigz -f test.txt.gz

Which results in test.txt.gz.gz

**Comment by madler** [comment]
I tried this with gzip 1.9, and it does the same thing. Both gzip and pigz with -f compress again to test.txt.gz.gz.
