### ISSUE TITLE
How can I compress a directory directly without tar

### ISSUE THREAD

**Issue by hangreenyue** [madler/pigz#78]
just like 'zip' command,Open the zip file in Windows and you'll see a folder directly,please

**Comment by neurolabusc** [comment]
You can't - the gz format compresses a single file, it can not be applied to multiple files/folders. As you note, you can pack multiple files/folders into a single .tar archive. The tar does not compress files/folders, it just concatenates them. You can subsequently compress the tar file to gz format.

**Comment by hangreenyue** [comment]
> You can't - the gz format compresses a single file, it can not be applied to multiple files/folders. As you note, you can pack multiple files/folders into a single .tar archive. The tar does not compress files/folders, it just concatenates them. You can subsequently compress the tar file to gz format.
do you know ipa file?Apple installation package is to use zip to compress a folder. Can I use pigz to compress Apple installation package?

**Comment by neurolabusc** [comment]
Most Apple graphical executables are distributed as a folder with the extension ".app". For example, on the Mac my MRIcroGL software is MRIcroGL.app with many files inside this folder (e.g. MRIcroGL.app/Contents/MacOS/MRIcroGL, MRIcroGL.app/Resources/dcm2niix, etc.). You can see that this is a folder not a single file by clicking on an application in the finder and choosing the "Show Package Contents" option. Since Apple .app folders contain multiple files, you can not compress them directly to .gz. You would need to archive as a .tar and next generate a .gz file.

**Comment by hangreenyue** [comment]
> Most Apple graphical executables are distributed as a folder with the extension ".app". For example, on the Mac my MRIcroGL software is MRIcroGL.app with many files inside this folder (e.g. MRIcroGL.app/Contents/MacOS/MRIcroGL, MRIcroGL.app/Resources/dcm2niix, etc.). You can see that this is a folder not a single file by clicking on an application in the finder and choosing the "Show Package Contents" option. Since Apple .app folders contain multiple files, you can not compress them directly to .gz. You would need to archive as a .tar and next generate a .gz file.

but apple phone can install .gz file?
