### ISSUE TITLE
Why is pigz renaming files inside .zip files?

### ISSUE THREAD

**Issue by ganzgustav22** [madler/pigz#84]
I have a file called "2020-05-27-raspios-buster-lite-armhf.zip", which contains a single file named "2020-05-27-raspios-buster-lite-armhf.img"

When I uncompress it with `pigz -d 2020-05-27-raspios-buster-lite-armhf.zip` I get a file named "2020-05-27-raspios-buster-lite-armhf", i.e. the .img extension is removed.

Why is that? I mean, this behaviour totally makes sense for "*.gz" files (with gzip only being able to compress single files and not having any filename info inside the archive and the "gunzip" command behaving the same) but absolutely not for zip files.

Edit: Oh, and the same thing with deletion, it deletes the .zip file after decompression. Makes sense for gzip files (gunzip also does it), but not for .zip files.

**Comment by madler** [comment]
It is a matter of opinion what does or does not make sense.

pigz should have consistent, predictable behavior regardless of the suffix on the file. For both .gz and .zip files, pigz will decompress to the name of that file, not the name stored in the header. gzip _does_ have a file name stored in the header, that is ignored by default. Note that pigz did not "remove" the .img extension. It used the name of the compressed file. If that same file were named "foo.zip", it would have extracted to the file "foo".

For both .gz and .zip files, pigz will delete the original once the file has been extracted.

Both behaviors can be changed by options, which both work the same way for .gz and .zip files. The `-k` of `--keep` option will keep the original compressed file. The `-N` or `--name` option will use the name in the header instead of the name of the compressed file.

So what you want is `pigz -dkN 2020-05-27-raspios-buster-lite-armhf.zip`, which will extract using the name in the zip headers, and which will not delete the .zip file.

**Comment by madler** [comment]
This report did bring me to realize an issue with .zip files with more than one entry. Since pigz only extracts the first entry of a .zip file, it should not delete the .zip file if there is more than one entry in it. This [commit](https://github.com/madler/pigz/commit/3b031d5f752b60c95553f1772eea4e7080860b62) fixes that.

**Comment by ganzgustav22** [comment]
Sorry, but this doesn't make sense at all. Especially not if it behaves different depending on if there is more than one file in the .zip.

.zip is not .gz, there is no consistency gained by making pigz behave on .zip files like gzip behaves on .gz files.

Actually, gunzip refuses to uncompress a .zip file. And no commandline tool or any other tool I've ever used to decompress a zip file deleted the zip file afterwards or changed the names of the contained files while uncompressing.

**Comment by madler** [comment]
No, gunzip will in fact do exactly the same thing. However you need to give it an option to recognize the .zip extension. `gunzip -S .zip whatever.zip` will extract the first entry from `whatever.zip`, calling it `whatever`, regardless of what the name is in the zip file, and will then delete `whatever.zip`.

**Comment by ganzgustav22** [comment]
> No, gunzip will in fact do exactly the same thing. However you need to give it an option to recognize the .zip extension. `gunzip -S .zip whatever.zip` will extract the first entry from `whatever.zip`, calling it `whatever`, regardless of what the name is in the zip file, and will then delete `whatever.zip`.

So, it will only do exactly the same thing if you explicitly tell it to do so with an extra parameter. This is clearly not the same behaviour.


Let me quote myself again:
>So, if I get a file, let's call it document.zip, with a single file contained in it named "Letter-to-Mr-important-Desk-1234.doc", then decompress it with pigz, I end up with:
An unzipped file called "document"
No original document.zip archive anymore
So there is absolutely no way to know the original filename anymore, one has to re-download the file (or worse, have to tell somebody to send a new USB memory stick via mail).

Do you _really_ think this is good default behaviour? Deleting people's files, although nobody expects that? Again, gunzip doesn't delete any .zip files unless you explicitly tell it that it should.
